version: '3.8'
services:
  angular:
    restart: always
    image: 372995092436.dkr.ecr.us-east-2.amazonaws.com/educasanare-frontend:latest
    # networks:
    #   - educasanare-frontend

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - angular
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf